name: Deploy DH22 via Direct Upload (Production)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Однократно (идемпотентно) создаём проект Pages.
      # Если уже существует — шаг пройдёт с предупреждением и мы не падаем.
      - name: Create Cloudflare Pages project (idempotent)
        uses: cloudflare/wrangler-action@v3
        continue-on-error: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages project create dh22 --production-branch=main

      # 2) Деплой статической папки public в Production (branch=main)
      - name: Deploy to Cloudflare Pages (Production)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=dh22 --branch=main --commit-hash=${{ github.sha }}
