name: Deploy DH22 (Next.js → Cloudflare Pages, Production)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build for Cloudflare Pages
        run: npx -y @cloudflare/next-on-pages@1.13.6

      - name: List build output (debug)
        run: |
          echo "=== .vercel/output ==="
          find .vercel/output -maxdepth 3 -type f | sort | head -n 200

      - name: Deploy to Cloudflare Pages (Production)
        run: npx wrangler@3 pages deploy ".vercel/output/static" --project-name="dh22" --branch="main"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
